language: node_js
node_js:
  - 9.10.1
before_script:
  - npm run build:dev
before_deploy:
  - npm run build:prod
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: ritualmap.com
    skip_cleanup: true
    local_dir: prod/public
  - provider: lambda
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    function_name: "addUser"
    region: "us-east-1"
    role: "arn:aws:iam::072629470284:role/service-role/ritualLambda"
    runtime: "nodejs8.10"
    module_name: "addUser"
    handler_name: "handler"
    zip: prod/lambdas/addUser.js
  - provider: lambda
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    function_name: "retrieveUser"
    region: "us-east-1"
    role: "arn:aws:iam::072629470284:role/service-role/ritualLambda"
    runtime: "nodejs8.10"
    module_name: "retrieveUser"
    handler_name: "handler"
    zip: prod/lambdas/retrieveUser.js
