export const ACTION_TYPES = {
	CREATE_RITUAL: 'CREATE_RITUAL',
	READ_RITUALS: 'READ_RITUALS',
	UPDATE_RITUAL: 'UPDATE_RITUAL',
	DELETE_RITUAL: 'DELETE_RITUAL',
	CREATE_COMPLETION: 'CREATE_COMPLETION',
	READ_COMPLETION: 'READ_COMPLETION',
	UPDATE_COMPLETION: 'UPDATE_COMPLETION',
	DELETE_COMPLETION: 'DELETE_COMPLETION',
}







